version: '2'
services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: cms_nginx
    restart: always
    depends_on:
      - postgres
      - php
      - rabbit
      - adminer
    volumes:
      - ../:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8081:80
    networks:
      - cms_network

  postgres:
    image: postgres
    hostname: postgres
    container_name: cms_postgres
    restart: always
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_PASSWORD=etyetyQ15
    networks:
      - cms_network

  adminer:
    image: adminer
    hostname: postgres-adminer
    container_name: postgres-adminer
    restart: always
    ports:
      - 8083:8080
    networks:
      - cms_network

  php:
    build: .
    hostname: php
    container_name: cms_php
    restart: always
    volumes:
      - ../:/var/www/html
    networks:
      - cms_network

  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    ports:
      - "8084:5672"
      - "8085:15672"
    restart: always
    networks:
      - cms_network

networks:
  cms_network:
    driver: bridge
