<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/fr/admin.php
// Date: 2016-01-06 19:58:29
return array(
    'admin_panel' => 'Admin Panel',
    'dashboard' => 'Dashboard',
    'users' => 'Users',
    'admins' => 'Admins',
    'settings' => 'Settings',
    'access' => 'Access',
    'permissions' => 'Permissions',
    'roles' => 'Roles',
    'translate' => 'translate',
    'translate_general' => 'translate_general',
    'edit_frontpage' => 'edit_frontpage',
    'edit_recipes' => 'edit_recipes',
    'logs' => 'logs',
    'clearcache' => 'clearcache',
);