<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/fr/auth.php
// Date: 2016-01-06 19:58:29
return array(
    'failed' => 'These credentials do not match our records.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
);