<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/fr/pagination.php
// Date: 2016-01-06 19:58:29
return array(
    'previous' => '&laquo; Previous',
    'next' => 'Next &raquo;',
);