<?php
// Generated by Translations Manager - Hpolthof\Translation
// File: lang/fr/passwords.php
// Date: 2016-01-06 19:58:29
return array(
    'password' => 'Passwords must be at least six characters and match the confirmation.',
    'reset' => 'Your password has been reset!',
    'sent' => 'We have e-mailed your password reset link!',
    'token' => 'This password reset token is invalid.',
    'user' => 'We can\'t find a user with that e-mail address.',
);